---

name: Day Outdoor Lights
entities:
  light.driveway_lantern_light:
    state: off
    transition: 5
  automation.reset_outdoor_lights_night:
    state: off
  automation.motion_stopped_outdoors:
    state: off
  automation.motion_detected_outdoors:
    state: off
