esphome:
  name: office
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.71
    subnet: 255.255.255.0
    gateway: 192.168.1.1

status_led:
    pin: 16

sensor:
  - platform: dht
    pin: 14
    temperature:
      name: "Office Temperature"
    humidity:
      name: "Office Humidity"
    model: DHT22
    update_interval: 60s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

text_sensor:
  - platform: version
    name: esphome_office_esphome_version
