---

esphome:
  name: sound_machine
  platform: ESP8266
  board: nodemcuv2

uart:
  tx_pin: D2
  rx_pin: D5
  baud_rate: 9600

dfplayer:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.73
    subnet: 255.255.255.0
    gateway: 192.168.1.1

status_led:
  pin: D0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Switches for tracks to play
switch:
  - platform: template
    name: "Waves Crashing"
    id: waves_crashing
    optimistic: true
    turn_on_action:
      then:
        - switch.turn_off: waves_and_kids
        - delay: 1s
        - dfplayer.play:
            file: 1
            loop: true
    turn_off_action:
      then:
        - dfplayer.stop
  - platform: template
    name: "Waves and Kids"
    id: waves_and_kids
    turn_on_action:
      then:
        - switch.turn_off: waves_crashing
        - delay: 1s
        - dfplayer.play:
            file: 2
            loop: true
    optimistic: true
    turn_off_action:
      then:
        - dfplayer.stop

# Physical buttons for local override
binary_sensor:
  - platform: gpio
    name: Button
    internal: true
    pin:
      number: 5
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_release:
      then:
        - switch.toggle: waves_crashing
  - platform: gpio
    name: Button
    internal: true
    pin:
      number: 12
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_release:
      then:
        - switch.toggle: waves_and_kids

text_sensor:
  - platform: version
    name: Sound Machine ESPHome Version
