---

house_climate:
  name: House Climate
  entities:
    - sensor.garage_temperature
    - sensor.office_temperature
    - sensor.office_temperature_target
    - sensor.garage_humidity
    - sensor.office_humidity
