---

house_climate:
  name: House Climate
  entities:
    - sensor.garage_temperature
    - sensor.office_temperature
    - sensor.office_temperature_target
    - sensor.garage_humidity
    - sensor.office_humidity
    - sensor.master_bathroom_multisensor_temperature
    - sensor.master_bathroom_multisensor_relative_humidity
    - sensor.master_bathroom_multisensor_luminance
    - sensor.master_bathroom_multisensor_ultraviolet
