---

motion_sensors:
  name: Motion Sensors
  entities:
    - binary_sensor.driveway_motion_sensor
    - sensor.driveway_motion_sensor_burglar
    - sensor.driveway_motion_sensor_battery
    - binary_sensor.driveway_motion_sensor_battery_low
