---

sprinklers:
  name: Sprinkler System
  entities:
    - switch.sprinkler_zone_1
    - switch.sprinkler_zone_2
    - switch.sprinkler_zone_3
    - switch.sprinkler_zone_4
    - switch.sprinkler_zone_5
    - switch.sprinkler_zone_6
    - switch.sprinkler_zone_7
    - switch.sprinkler_zone_8
