---

weather:
  name: Weather
  entities:
    - sun.sun
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_humidity
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_temperature
    - sensor.dark_sky_uv_index
    - sensor.dark_sky_wind_speed
