---

log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: !secret ha_url
      token: !secret token
hadashboard:
  dash_url: "http://192.168.1.2:5050"
