---

sprinkler_water_backyard:
  alias: "Sprinkler Water Backyard"
  sequence:
    - service: switch.turn_off
      entity_id: group.sprinklers
    - delay: '00:01'
    - service: switch.turn_on
      entity_id: switch.sprinkler_zone_2
    - delay: '00:40'
    - service: switch.turn_off
      entity_id: switch.sprinkler_zone_2
    - delay: '00:01'
    - service: switch.turn_on
      entity_id: switch.sprinkler_zone_3
    - delay: '00:40'
    - service: switch.turn_off
      entity_id: switch.sprinkler_zone_3
    - delay: '00:01'
    - service: switch.turn_on
      entity_id: switch.sprinkler_zone_5
    - delay: '00:40'
    - service: switch.turn_off
      entity_id: switch.sprinkler_zone_5
