---

vacuum_nursery:
  alias: "Vacuum Nursery"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[19538, 38237, 22988, 44737, 1]]
