---

vacuum_kitchen_hallway:
  alias: "Vacuum Kitchen Hallway"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[15385, 30719, 16585, 39669, 1]]
