---

vacuum_living_room:
  alias: "Vacuum Living Room"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[15361, 24666, 20361, 31666, 1]]
