---

vacuum_kitchen:
  alias: "Vacuum Kitchen"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[12435,32906,16785,37456,2]]
