---

vacuum_back_hallway:
  alias: "Vacuum Back Hallway"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[15340, 36881, 19290, 39631, 1]]
