---

vacuum_master_bedroom:
  alias: "Vacuum Master Bedroom"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[24704, 29229, 29304, 34179, 1]]
