---

vacuum_master_bathroom:
  alias: "Vacuum Master Bathroom"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[24417,33953,29067,38053,1]]
