---

vacuum_nursery:
  alias: "Vacuum Nursery"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[17945, 37840, 22795, 44540, 1]]
