---

vacuum_office:
  alias: "Vacuum Office"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[21988, 24333, 27088, 29083, 1]]
