---

vacuum_dining_room:
  alias: "Vacuum Dining Room"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[12156, 26890, 15356, 32890, 1]]
