---

vacuum_laundry_room:
  alias: "Vacuum Laundry Room"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[12119, 37773, 15519, 39673, 1]]
