---

vacuum_entryway:
  alias: "Vacuum Entryway"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[19915, 26689, 22215, 32089, 2]]
