---
# Vacuums all the hallways in the house.
#
# 1. Entryway
# 2. Front Hallway
# 3. Living Room Hallway
# 4. Kitchen Hallway
# 5. Back Hallway

vacuum_hallways:
  alias: "Vacuum Hallways"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[20375, 27001, 22275, 31801, 1], [20235, 30545, 24635, 31745, 1], [15361, 29916, 20311, 31666, 1], [15385, 30719, 16585, 39669, 1], [15340, 36881, 19290, 39631, 1]]
