---

vacuum_living_room_hallway:
  alias: "Vacuum Living Room Hallway"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[15276,29890,20576,31590,1]]
