---

vacuum_guest_bedroom:
  alias: "Vacuum Guest Bedroom"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[12057, 39816, 16457, 44716, 1]]
