---

vacuum_kitchen_hallway:
  alias: "Vacuum Kitchen Hallway"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[15119,30451,16419,39551,1]]
