---

vacuum_front_hallway:
  alias: "Vacuum Front Hallway"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[19941,28834,24541,31634,1]]
