---
# Vacuums all the hallways in the house.
#
# 1. Entryway
# 2. Front Hallway
# 3. Living Room Hallway
# 4. Kitchen Hallway
# 5. Back Hallway

vacuum_hallways:
  alias: "Vacuum Hallways"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[19915,26689,22215,32089,1]],[[19941,28834,24541,31634,1]],[[15276,29890,20576,31590,1]],[[15119,30451,16419,39551,1]],[[16265,37878,19215,39528,1]]
