---

exclude: ^config/homeassistant/custom_components/hacs/
exclude: ^config/homeassistant/www/community/

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: config/homeassistant/.HA_VERSION
        exclude: config/homeassistant/custom_components
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
        exclude: config/homeassistant/custom_components
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: sort-simple-yaml
  - repo: https://github.com/IamTheFij/docker-pre-commit.git
    rev: v1.0.0
    hooks:
      - id: docker-compose-check
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
  - repo: https://github.com/psf/black.git
    rev: 19.3b0
    hooks:
      - id: black
