---

version: "3"

services:
  homeassistant:
    image: homeassistant/home-assistant:0.101.3
    user: 1000:1000
    volumes:
      - ./config/homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro
      - /tmp/gifs:/camera_gifs
    network_mode: "host"
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave:rmw"
    command: ["/config/run"]
    depends_on:
      - influxdb
      - mosquitto
  postgres:
    image: postgres:11.4
    user: 1000:1000
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=homeassistant
      - POSTGRES_USER=homeassistant
      - POSTGRES_DB=homeassistant
  pgadmin:
    image: thajeztah/pgadmin4:3.6
    user: 1000:1000
    ports:
      - "8087:5050"
    volumes:
      - ./config/pgadmin:/pgadmin
  appdaemon:
    image: acockburn/appdaemon:3.0.5
    user: 1000:1000
    volumes:
      - ./config/appdaemon:/conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5050:5050"
    depends_on:
      - homeassistant
  influxdb:
    image: influxdb:1.7.6
    user: 1000:1000
    volumes:
      - ./config/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_DB=home_assistant"
  grafana:
    image: grafana/grafana:6.2.5
    user: 1000:1000
    volumes:
      - ./config/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
  mosquitto:
    image: eclipse-mosquitto:1.6.3
    user: 1000:1000
    volumes:
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
  openzwave:
    image: openzwave/openzwave-control-panel
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0:rmw"
    volumes:
      - ./config/homeassistant/options.xml:/config/options.xml
      - ./config/zwcfg_0xe4665338.xml:/config/zwcfg_0xe4665338.xml
    ports:
      - "8008:8008"
  portainer:
    image: portainer/portainer:1.21.0
    user: 1000:999
    volumes:
      - ./config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    ports:
      - "9000:9000"
  esphome:
    image: esphome/esphome:1.13.6
    user: 1000:1000
    volumes:
      - ./config/homeassistant/esphome:/config
    network_mode: "host"
  zwave2mqtt:
    image: robertslando/zwave2mqtt:latest
    user: 1000:1000
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave:rmw"
    volumes:
      - ./config/zwave2mqtt/store:/usr/src/app/store
      - ./config/homeassistant/openzwave_config:/openzwave_config
    ports:
      - "8091:8091"
  icbinv:
    image: dmkif/icantbelieveitsnotvaletudo:latest
    user: 1000:1000
    volumes:
      - ./config/icbinv/config.json:/app/config.json
    network_mode: "host"
