---

alias: Office Fan Turn On
initial_state: false
trigger:
  - platform: state
    entity_id: sensor.office_temperature
  - platform: state
    entity_id: sensor.office_temperature_target
condition:
  - condition: state
    entity_id: timer.office_fan_cooldown
    state: 'idle'
action:
  - service: fan.turn_on
    entity_id: fan.office_fan_switch_level
    data_template:
        speed: >-
          {% if (((states('sensor.office_temperature_target') | float) - (states('sensor.office_temperature') | float))) >= 1.0 %}
            low
          {% elif (((states('sensor.office_temperature_target') | float) - (states('sensor.office_temperature') | float))) <= -3.0 %}
            high
          {% else %}
            medium
          {% endif %}
  - service: timer.start
    entity_id: timer.office_fan_cooldown
