---

alias: Office Fan Turn Off
trigger:
  - platform: state
    entity_id: input_boolean.turn_on_office_fan_automation
    to: 'off'
action:
  - service: fan.turn_off
    entity_id: fan.office_fan_switch_level

