---

alias: Motion Stopped Outdoors
initial_state: false
trigger:
  - platform: state
    entity_id: binary_sensor.driveway_motion_sensor
    to: 'off'
action:
  - service: timer.start
    entity_id: timer.reset_outdoor_lights
