---

alias: Water Backyard
trigger:
  - platform: sun
    event: sunrise
    offset: "-01:30:00"
condition:
  - condition: time
    weekday:
      - tue
      - sat
  - condition: numeric_state
    entity_id: "sensor.dark_sky_precip_probability_0d"
    below: 60
action:
  - service: script.sprinkler_water_backyard
