---

alias: Water Backyard
trigger:
  - platform: sun
    event: sunrise
    offset: "-01:00:00"
condition:
  - condition: time
    weekday:
      - thu
      - sun
action:
  - service: script.sprinkler_water_backyard
