---

- platform: deluge
  host: 192.168.1.2
  username: !secret deluge_username
  password: !secret deluge_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
