---

platform: template
switches:
  office_fan_speed_switch:
    friendly_name: "Office Fan Speed Switch"
    entity_id:
      - climate.office
      - sensor.office_temperature
      - fan.office_fan_switch_level
    value_template: "{{ is_state('fan.office_fan_switch_level', 'on') }}"
    turn_on:
      service: fan.turn_on
      data_template:
        entity_id: fan.office_fan_switch_level
        speed: >-
          {% if ((state_attr('climate.office', 'temperature')|float) - (states.sensor.office_temperature|float)) >= 1.0 %}
            low
          {% elif ((state_attr('climate.office', 'temperature')|float) - (states.sensor.office_temperature|float)) <= -3 %}
            high
          {% else %}
            medium
          {% endif %}
    turn_off:
      service: fan.turn_off
      data:
        entity_id: fan.office_fan_switch_level
