---

platform: template
switches:
  office_thermostat_switch:
    value_template:  "{{ is_state('automation.office_fan_turn_on', 'on') }}"
    turn_on:
      service: automation.turn_on
      entity: automation.office_fan_turn_on
    turn_off:
      - service: automation.turn_off
        entity_id: automation.office_fan_turn_on
      - service: fan.turn_off
        entity_id: fan.office_fan_switch_level

