---

alias: Check if Garage Door Closed
trigger:
  - platform: time
    at: '21:05:00'
condition:
  - condition: state
    entity_id: cover.garage_door
    state: 'open'
action:
  - service: notify.zack_telegram
    data:
      title: "Garage Door"
      message: "The garage door is open!"
