---

alias: IFTTT Stop Vacuuming
trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
condition:
  condition: template
  value_template: "{{ trigger.event.data.service == 'vacuum.return_to_base' }}"
action:
  service_template: '{{ trigger.event.data.service }}'
  data_template:
    entity_id: '{{ trigger.event.data.entity_id }}'
