---

path: inside
title: Inside
icon: mdi:sofa
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.office_lights
          - light.living_room_light
          - light.kitchen_lights
          - light.nursery_string_lights
      - type: entities
        title: Fans
        show_header_toggle: false
        entities:
          - fan.office_fan_switch_level
  - type: thermostat
    entity: climate.office
  - type: "custom:valetudo-map-card"
    entity: sensor.valetudo_map
    rotate: 0
    crop:
      top: 70
      bottom: 70
      left: 20
      right: 20
    min_height: 0
