---

name: Morning
entities:
  light.kitchen_lights:
    state: true
  light.living_room_light:
    state: true
    brightness_pct: 20
  light.office_lamp_left:
    state: true
  switch.flux:
    state: true
