---
# The recorder component is storing details in a database which
# then are handled by the history component.
#
# https://www.home-assistant.io/components/recorder/
#
recorder:

  # Use a higher performance database for data
  db_url: !secret database

  # The number of days of history to keep in the recorder database
  purge_keep_days: 3

  # How often (in days) the purge task runs
  purge_interval: 1

  # Ignore some entities that generate lots of data and aren't useful
  exclude:
    entities:
      - sensor.plug_1_uptime
      - sensor.sound_machine_uptime
      - sensor.time_until_next_longhorn_game
