---
# The vacuum component enables the ability to control home cleaning robots
# within Home Assistant.
#
# https://www.home-assistant.io/components/vacuum
#

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.12
    token: !secret xiaomi_miio_vacuum_token
