---
# Adds an iframe panel to the Home Assistant frontend for ESPHome.
# This allows me to access ESPHome straight from Home Asssitant's UI
#
# https://www.home-assistant.io/components/panel_iframe/
#
esphome:
  title: ESPHome
  icon: mdi:chip
  url: !secret panel_iframe_esphome_url
