---
# Adds an iframe panel to the Home Assistant frontend for Grafana.
# This allows me to access Grafana straight from Home Asssitant's UI
#
# https://www.home-assistant.io/components/panel_iframe/
#
grafana:
  title: Grafana
  icon: mdi:chart-timeline
  url: !secret panel_iframe_grafana_url
